[metadata]
name = DMDO
version = 2601.2
author = Ahmed H. Bayoumy
author_email = ahmed.bayoumy@mail.mcgill.ca
description = "Python package for DMDO; an implementation of the Nonhierarchical Analytical Target Cascading (NHATC.)"
long_description = file: README.md
long_description_content_type = text/markdown
license = GPL-3.0-or-later
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent
    Intended Audience :: Developers

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10


[options.packages.find]
where = src

[options.extras_require]
testing =
    pytest>=6.0
    pytest-cov>=2.0
    mypy>=0.910
    flake8>=3.910
    tox>=3.24

[options.package_data]
OMADS = py.typed

[flake8]
max-line-length = 100